---
- name: SNS Message Sender
  hosts: all
  gather_facts: no
  connection: local

  vars:
    message_file:
# files are in .txt as they need to replace the variables e.g. 'stack_prefix' (un-quoted) which breaks the json validation.
# if the variables were in double quotes, they would not be replaced with the value.
    message: "{{ lookup('file', message_file) }}"

  tasks:

    - debug:
        msg: "Send message: {{ message }} with subject: {{ subject }} to topic: {{ sns_topic }} in region: {{ aws_region }}"

    - name: Send message to SNS Topic {{ sns_topic }}
      sns:
        msg: "{{ message }}"
        subject: "{{ subject }}"
        topic: "{{ sns_topic }}"
        region: "{{ aws_region }}"
      when: message.task != 'offline-snapshot'
      delegate_to: localhost

    - name: Send message to SNS Topic {{ backup_sns_topic | default(sns_topic) }}
      sns:
        msg: "{{ message }}"
        subject: "{{ subject }}"
        topic: "{{ backup_sns_topic | default(sns_topic) }}"
        region: "{{ aws_region }}"
      when: "message.task == 'offline-snapshot'"
      delegate_to: localhost
