---
- name: SNS Message Sender
  hosts: all
  gather_facts: no
  connection: local

  vars:
    message_file:
# files are in .txt as they need to replace the variables e.g. 'stack_prefix' (un-quoted) which breaks the json validation.
# if the variables were in double quotes, they would not be replaced with the value.
    message: "{{ lookup('file', message_file) }}"

  tasks:

    - debug:
        msg: "Send message: {{ message }} with subject: {{ subject }} to topic: {{ sns_topic }} in region: {{ aws_region }}"

    - name: Send message to SNS Topic
      sns:
        msg: "{{ message }}"
        subject: "{{ subject }}"
        topic: "{{ sns_topic }}"
        region: "{{ aws_region }}"
      register: publish_message

    - name: Scan if message was send out by Lambda
      dynamodb_search:
        table_name: "{{ dynamodb_tablename }}"
        attribute: message_id
        attribute_value: "{{ publish_message.item.PublishResponse.PublishResult.MessageId }}"
        get_attribute: command_id
        select: SPECIFIC_ATTRIBUTES
        comparisonoperator: EQ
        state: scan
      register: dbscan
      until: dbscan.item != []
      retries: 120
      delay: 5

    - set_fact:
        cmd_id: "{{ item.command_id.S }}"
      with_items:
        "{{ dbscan.item }}"

    - name: Query state
      dynamodb_search:
        table_name: michaelb-aem63-AemStackManagerTable
        attribute: command_id
        attribute_value: "{{ cmd_id }}"
        get_attribute: state
        select: SPECIFIC_ATTRIBUTES
        comparisonoperator: EQ
        state: query
      register: dbquery
      until: dbquery.item[0].state.S != "Pending"
      # The retry values should mirror the TTL of the ssm.send_command of the Lambda function.
      retries: 120
      delay: 5

    - name: Get path to output files
      aws_s3:
        mode: list
        bucket: "{{ s3.bucket }}"
        prefix: "{{ stack_prefix }}/stack-manager/SSMOutput/{{ cmd_id }}"
      register: output_files

    - name: Set facts for getting command output
      set_fact:
        log_path: "{{ playbook_dir }}/logs/"
        dl_path: "{{ stack_prefix }}/stack-manager/SSMOutput/{{ cmd_id }}"
        s3_files: "{{ output_files.s3_keys }}"

    - debug: msg="{{ s3_files }}"

    - name: "Create Download directory in {{log_path }}{{ dl_path }}"
      file:
        path: "{{ log_path }}{{ item|regex_replace('(stdout|stderr)$', '') }}"
        state: directory
      with_items:
        - "{{ s3_files }}"

    - name: "Save command output to {{log_path }}{{ dl_path }}"
      aws_s3:
        mode: get
        bucket: aem-stack-builder
        object: "{{ item }}"
        dest: "{{ log_path }}{{ item }}"
      with_items:
        - "{{ s3_files }}"
      register: saved_files

    - name: "Find error log files in {{log_path }}{{ dl_path }}"
      find:
        paths: "{{log_path }}{{ dl_path }}"
        file_type: file
        patterns: stderr
        recurse: yes
      register: stderr_files

    - log_output:
        type: file
        state: info
        log_files: "{{ stderr_files.files | map(attribute='path')|list }}"
